# application.properties

spring.application.name=enterprise-procurement

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_procurement
spring.datasource.username=postgres
spring.datasource.password=sunil

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.fail-on-empty-beans=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=ChangeThisToA256BitSecretKeyForProduction1234567890
jwt.expiration=86400000